/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinarRouteImport } from './routes/treinar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinarIndexRouteImport } from './routes/treinar/index'
import { Route as TreinarTurmaRouteImport } from './routes/treinar/turma'
import { Route as TreinarPersonalRouteImport } from './routes/treinar/personal'
import { Route as TreinarMuaythaiRouteImport } from './routes/treinar/muaythai'
import { Route as TreinarPersonalIndexRouteImport } from './routes/treinar/personal/index'
import { Route as TreinarMuaythaiIndexRouteImport } from './routes/treinar/muaythai/index'
import { Route as TreinarPersonalAgendarRouteImport } from './routes/treinar/personal/agendar'
import { Route as TreinarMuaythaiAgendarRouteImport } from './routes/treinar/muaythai/agendar'

const TreinarRoute = TreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarIndexRoute = TreinarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarTurmaRoute = TreinarTurmaRouteImport.update({
  id: '/turma',
  path: '/turma',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarPersonalRoute = TreinarPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarMuaythaiRoute = TreinarMuaythaiRouteImport.update({
  id: '/muaythai',
  path: '/muaythai',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarPersonalIndexRoute = TreinarPersonalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarPersonalRoute,
} as any)
const TreinarMuaythaiIndexRoute = TreinarMuaythaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarMuaythaiRoute,
} as any)
const TreinarPersonalAgendarRoute = TreinarPersonalAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => TreinarPersonalRoute,
} as any)
const TreinarMuaythaiAgendarRoute = TreinarMuaythaiAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => TreinarMuaythaiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/treinar': typeof TreinarRouteWithChildren
  '/treinar/muaythai': typeof TreinarMuaythaiRouteWithChildren
  '/treinar/personal': typeof TreinarPersonalRouteWithChildren
  '/treinar/turma': typeof TreinarTurmaRoute
  '/treinar/': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/muaythai/': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal/': typeof TreinarPersonalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/treinar/turma': typeof TreinarTurmaRoute
  '/treinar': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/muaythai': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal': typeof TreinarPersonalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/treinar': typeof TreinarRouteWithChildren
  '/treinar/muaythai': typeof TreinarMuaythaiRouteWithChildren
  '/treinar/personal': typeof TreinarPersonalRouteWithChildren
  '/treinar/turma': typeof TreinarTurmaRoute
  '/treinar/': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/muaythai/': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal/': typeof TreinarPersonalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/treinar'
    | '/treinar/muaythai'
    | '/treinar/personal'
    | '/treinar/turma'
    | '/treinar/'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/muaythai/'
    | '/treinar/personal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/treinar/turma'
    | '/treinar'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/muaythai'
    | '/treinar/personal'
  id:
    | '__root__'
    | '/'
    | '/treinar'
    | '/treinar/muaythai'
    | '/treinar/personal'
    | '/treinar/turma'
    | '/treinar/'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/muaythai/'
    | '/treinar/personal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreinarRoute: typeof TreinarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinar': {
      id: '/treinar'
      path: '/treinar'
      fullPath: '/treinar'
      preLoaderRoute: typeof TreinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar/': {
      id: '/treinar/'
      path: '/'
      fullPath: '/treinar/'
      preLoaderRoute: typeof TreinarIndexRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/turma': {
      id: '/treinar/turma'
      path: '/turma'
      fullPath: '/treinar/turma'
      preLoaderRoute: typeof TreinarTurmaRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/personal': {
      id: '/treinar/personal'
      path: '/personal'
      fullPath: '/treinar/personal'
      preLoaderRoute: typeof TreinarPersonalRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/muaythai': {
      id: '/treinar/muaythai'
      path: '/muaythai'
      fullPath: '/treinar/muaythai'
      preLoaderRoute: typeof TreinarMuaythaiRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/personal/': {
      id: '/treinar/personal/'
      path: '/'
      fullPath: '/treinar/personal/'
      preLoaderRoute: typeof TreinarPersonalIndexRouteImport
      parentRoute: typeof TreinarPersonalRoute
    }
    '/treinar/muaythai/': {
      id: '/treinar/muaythai/'
      path: '/'
      fullPath: '/treinar/muaythai/'
      preLoaderRoute: typeof TreinarMuaythaiIndexRouteImport
      parentRoute: typeof TreinarMuaythaiRoute
    }
    '/treinar/personal/agendar': {
      id: '/treinar/personal/agendar'
      path: '/agendar'
      fullPath: '/treinar/personal/agendar'
      preLoaderRoute: typeof TreinarPersonalAgendarRouteImport
      parentRoute: typeof TreinarPersonalRoute
    }
    '/treinar/muaythai/agendar': {
      id: '/treinar/muaythai/agendar'
      path: '/agendar'
      fullPath: '/treinar/muaythai/agendar'
      preLoaderRoute: typeof TreinarMuaythaiAgendarRouteImport
      parentRoute: typeof TreinarMuaythaiRoute
    }
  }
}

interface TreinarMuaythaiRouteChildren {
  TreinarMuaythaiAgendarRoute: typeof TreinarMuaythaiAgendarRoute
  TreinarMuaythaiIndexRoute: typeof TreinarMuaythaiIndexRoute
}

const TreinarMuaythaiRouteChildren: TreinarMuaythaiRouteChildren = {
  TreinarMuaythaiAgendarRoute: TreinarMuaythaiAgendarRoute,
  TreinarMuaythaiIndexRoute: TreinarMuaythaiIndexRoute,
}

const TreinarMuaythaiRouteWithChildren = TreinarMuaythaiRoute._addFileChildren(
  TreinarMuaythaiRouteChildren,
)

interface TreinarPersonalRouteChildren {
  TreinarPersonalAgendarRoute: typeof TreinarPersonalAgendarRoute
  TreinarPersonalIndexRoute: typeof TreinarPersonalIndexRoute
}

const TreinarPersonalRouteChildren: TreinarPersonalRouteChildren = {
  TreinarPersonalAgendarRoute: TreinarPersonalAgendarRoute,
  TreinarPersonalIndexRoute: TreinarPersonalIndexRoute,
}

const TreinarPersonalRouteWithChildren = TreinarPersonalRoute._addFileChildren(
  TreinarPersonalRouteChildren,
)

interface TreinarRouteChildren {
  TreinarMuaythaiRoute: typeof TreinarMuaythaiRouteWithChildren
  TreinarPersonalRoute: typeof TreinarPersonalRouteWithChildren
  TreinarTurmaRoute: typeof TreinarTurmaRoute
  TreinarIndexRoute: typeof TreinarIndexRoute
}

const TreinarRouteChildren: TreinarRouteChildren = {
  TreinarMuaythaiRoute: TreinarMuaythaiRouteWithChildren,
  TreinarPersonalRoute: TreinarPersonalRouteWithChildren,
  TreinarTurmaRoute: TreinarTurmaRoute,
  TreinarIndexRoute: TreinarIndexRoute,
}

const TreinarRouteWithChildren =
  TreinarRoute._addFileChildren(TreinarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreinarRoute: TreinarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
