/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinarRouteImport } from './routes/treinar'
import { Route as TreinarIndexRouteImport } from './routes/treinar/index'
import { Route as TreinarMuaythaiRouteImport } from './routes/treinar/muaythai'
import { Route as TreinarPersonalRouteImport } from './routes/treinar/personal'
import { Route as TreinarTurmaRouteImport } from './routes/treinar/turma'
import { Route as TreinarMuaythaiIndexRouteImport } from './routes/treinar/muaythai/index'
import { Route as TreinarMuaythaiAgendarRouteImport } from './routes/treinar/muaythai/agendar'
import { Route as TreinarPersonalIndexRouteImport } from './routes/treinar/personal/index'
import { Route as TreinarPersonalAgendarRouteImport } from './routes/treinar/personal/agendar'
import { Route as TreinarTurmaIndexRouteImport } from './routes/treinar/turma/index'
import { Route as TreinarTurmaCtIshigekiRouteImport } from './routes/treinar/turma/ct-ishigeki'
import { Route as TreinarTurmaStudioTopFitnessRouteImport } from './routes/treinar/turma/studio-top-fitness'
import { Route as TreinarTurmaCtIshigekiIndexRouteImport } from './routes/treinar/turma/ct-ishigeki/index'
import { Route as TreinarTurmaCtIshigekiInteresseRouteImport } from './routes/treinar/turma/ct-ishigeki/interesse'
import { Route as TreinarTurmaStudioTopFitnessIndexRouteImport } from './routes/treinar/turma/studio-top-fitness/index'
import { Route as TreinarTurmaStudioTopFitnessInteresseRouteImport } from './routes/treinar/turma/studio-top-fitness/interesse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarRoute = TreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarIndexRoute = TreinarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarMuaythaiRoute = TreinarMuaythaiRouteImport.update({
  id: '/muaythai',
  path: '/muaythai',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarPersonalRoute = TreinarPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarTurmaRoute = TreinarTurmaRouteImport.update({
  id: '/turma',
  path: '/turma',
  getParentRoute: () => TreinarRoute,
} as any)
const TreinarMuaythaiIndexRoute = TreinarMuaythaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarMuaythaiRoute,
} as any)
const TreinarMuaythaiAgendarRoute = TreinarMuaythaiAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => TreinarMuaythaiRoute,
} as any)
const TreinarPersonalIndexRoute = TreinarPersonalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarPersonalRoute,
} as any)
const TreinarPersonalAgendarRoute = TreinarPersonalAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => TreinarPersonalRoute,
} as any)
const TreinarTurmaIndexRoute = TreinarTurmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinarTurmaRoute,
} as any)
const TreinarTurmaCtIshigekiRoute = TreinarTurmaCtIshigekiRouteImport.update({
  id: '/ct-ishigeki',
  path: '/ct-ishigeki',
  getParentRoute: () => TreinarTurmaRoute,
} as any)
const TreinarTurmaStudioTopFitnessRoute =
  TreinarTurmaStudioTopFitnessRouteImport.update({
    id: '/studio-top-fitness',
    path: '/studio-top-fitness',
    getParentRoute: () => TreinarTurmaRoute,
  } as any)
const TreinarTurmaCtIshigekiIndexRoute =
  TreinarTurmaCtIshigekiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TreinarTurmaCtIshigekiRoute,
  } as any)
const TreinarTurmaCtIshigekiInteresseRoute =
  TreinarTurmaCtIshigekiInteresseRouteImport.update({
    id: '/interesse',
    path: '/interesse',
    getParentRoute: () => TreinarTurmaCtIshigekiRoute,
  } as any)
const TreinarTurmaStudioTopFitnessIndexRoute =
  TreinarTurmaStudioTopFitnessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TreinarTurmaStudioTopFitnessRoute,
  } as any)
const TreinarTurmaStudioTopFitnessInteresseRoute =
  TreinarTurmaStudioTopFitnessInteresseRouteImport.update({
    id: '/interesse',
    path: '/interesse',
    getParentRoute: () => TreinarTurmaStudioTopFitnessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/treinar': typeof TreinarRouteWithChildren
  '/treinar/muaythai': typeof TreinarMuaythaiRouteWithChildren
  '/treinar/personal': typeof TreinarPersonalRouteWithChildren
  '/treinar/turma': typeof TreinarTurmaRouteWithChildren
  '/treinar/': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/turma/ct-ishigeki': typeof TreinarTurmaCtIshigekiRouteWithChildren
  '/treinar/turma/studio-top-fitness': typeof TreinarTurmaStudioTopFitnessRouteWithChildren
  '/treinar/muaythai/': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal/': typeof TreinarPersonalIndexRoute
  '/treinar/turma/': typeof TreinarTurmaIndexRoute
  '/treinar/turma/ct-ishigeki/interesse': typeof TreinarTurmaCtIshigekiInteresseRoute
  '/treinar/turma/studio-top-fitness/interesse': typeof TreinarTurmaStudioTopFitnessInteresseRoute
  '/treinar/turma/ct-ishigeki/': typeof TreinarTurmaCtIshigekiIndexRoute
  '/treinar/turma/studio-top-fitness/': typeof TreinarTurmaStudioTopFitnessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/treinar': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/muaythai': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal': typeof TreinarPersonalIndexRoute
  '/treinar/turma': typeof TreinarTurmaIndexRoute
  '/treinar/turma/ct-ishigeki/interesse': typeof TreinarTurmaCtIshigekiInteresseRoute
  '/treinar/turma/studio-top-fitness/interesse': typeof TreinarTurmaStudioTopFitnessInteresseRoute
  '/treinar/turma/ct-ishigeki': typeof TreinarTurmaCtIshigekiIndexRoute
  '/treinar/turma/studio-top-fitness': typeof TreinarTurmaStudioTopFitnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/treinar': typeof TreinarRouteWithChildren
  '/treinar/muaythai': typeof TreinarMuaythaiRouteWithChildren
  '/treinar/personal': typeof TreinarPersonalRouteWithChildren
  '/treinar/turma': typeof TreinarTurmaRouteWithChildren
  '/treinar/': typeof TreinarIndexRoute
  '/treinar/muaythai/agendar': typeof TreinarMuaythaiAgendarRoute
  '/treinar/personal/agendar': typeof TreinarPersonalAgendarRoute
  '/treinar/turma/ct-ishigeki': typeof TreinarTurmaCtIshigekiRouteWithChildren
  '/treinar/turma/studio-top-fitness': typeof TreinarTurmaStudioTopFitnessRouteWithChildren
  '/treinar/muaythai/': typeof TreinarMuaythaiIndexRoute
  '/treinar/personal/': typeof TreinarPersonalIndexRoute
  '/treinar/turma/': typeof TreinarTurmaIndexRoute
  '/treinar/turma/ct-ishigeki/interesse': typeof TreinarTurmaCtIshigekiInteresseRoute
  '/treinar/turma/studio-top-fitness/interesse': typeof TreinarTurmaStudioTopFitnessInteresseRoute
  '/treinar/turma/ct-ishigeki/': typeof TreinarTurmaCtIshigekiIndexRoute
  '/treinar/turma/studio-top-fitness/': typeof TreinarTurmaStudioTopFitnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/treinar'
    | '/treinar/muaythai'
    | '/treinar/personal'
    | '/treinar/turma'
    | '/treinar/'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/turma/ct-ishigeki'
    | '/treinar/turma/studio-top-fitness'
    | '/treinar/muaythai/'
    | '/treinar/personal/'
    | '/treinar/turma/'
    | '/treinar/turma/ct-ishigeki/interesse'
    | '/treinar/turma/studio-top-fitness/interesse'
    | '/treinar/turma/ct-ishigeki/'
    | '/treinar/turma/studio-top-fitness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/treinar'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/muaythai'
    | '/treinar/personal'
    | '/treinar/turma'
    | '/treinar/turma/ct-ishigeki/interesse'
    | '/treinar/turma/studio-top-fitness/interesse'
    | '/treinar/turma/ct-ishigeki'
    | '/treinar/turma/studio-top-fitness'
  id:
    | '__root__'
    | '/'
    | '/treinar'
    | '/treinar/muaythai'
    | '/treinar/personal'
    | '/treinar/turma'
    | '/treinar/'
    | '/treinar/muaythai/agendar'
    | '/treinar/personal/agendar'
    | '/treinar/turma/ct-ishigeki'
    | '/treinar/turma/studio-top-fitness'
    | '/treinar/muaythai/'
    | '/treinar/personal/'
    | '/treinar/turma/'
    | '/treinar/turma/ct-ishigeki/interesse'
    | '/treinar/turma/studio-top-fitness/interesse'
    | '/treinar/turma/ct-ishigeki/'
    | '/treinar/turma/studio-top-fitness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreinarRoute: typeof TreinarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar': {
      id: '/treinar'
      path: '/treinar'
      fullPath: '/treinar'
      preLoaderRoute: typeof TreinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar/': {
      id: '/treinar/'
      path: '/'
      fullPath: '/treinar/'
      preLoaderRoute: typeof TreinarIndexRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/muaythai': {
      id: '/treinar/muaythai'
      path: '/muaythai'
      fullPath: '/treinar/muaythai'
      preLoaderRoute: typeof TreinarMuaythaiRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/personal': {
      id: '/treinar/personal'
      path: '/personal'
      fullPath: '/treinar/personal'
      preLoaderRoute: typeof TreinarPersonalRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/turma': {
      id: '/treinar/turma'
      path: '/turma'
      fullPath: '/treinar/turma'
      preLoaderRoute: typeof TreinarTurmaRouteImport
      parentRoute: typeof TreinarRoute
    }
    '/treinar/muaythai/': {
      id: '/treinar/muaythai/'
      path: '/'
      fullPath: '/treinar/muaythai/'
      preLoaderRoute: typeof TreinarMuaythaiIndexRouteImport
      parentRoute: typeof TreinarMuaythaiRoute
    }
    '/treinar/muaythai/agendar': {
      id: '/treinar/muaythai/agendar'
      path: '/agendar'
      fullPath: '/treinar/muaythai/agendar'
      preLoaderRoute: typeof TreinarMuaythaiAgendarRouteImport
      parentRoute: typeof TreinarMuaythaiRoute
    }
    '/treinar/personal/': {
      id: '/treinar/personal/'
      path: '/'
      fullPath: '/treinar/personal/'
      preLoaderRoute: typeof TreinarPersonalIndexRouteImport
      parentRoute: typeof TreinarPersonalRoute
    }
    '/treinar/personal/agendar': {
      id: '/treinar/personal/agendar'
      path: '/agendar'
      fullPath: '/treinar/personal/agendar'
      preLoaderRoute: typeof TreinarPersonalAgendarRouteImport
      parentRoute: typeof TreinarPersonalRoute
    }
    '/treinar/turma/': {
      id: '/treinar/turma/'
      path: '/'
      fullPath: '/treinar/turma/'
      preLoaderRoute: typeof TreinarTurmaIndexRouteImport
      parentRoute: typeof TreinarTurmaRoute
    }
    '/treinar/turma/ct-ishigeki': {
      id: '/treinar/turma/ct-ishigeki'
      path: '/ct-ishigeki'
      fullPath: '/treinar/turma/ct-ishigeki'
      preLoaderRoute: typeof TreinarTurmaCtIshigekiRouteImport
      parentRoute: typeof TreinarTurmaRoute
    }
    '/treinar/turma/studio-top-fitness': {
      id: '/treinar/turma/studio-top-fitness'
      path: '/studio-top-fitness'
      fullPath: '/treinar/turma/studio-top-fitness'
      preLoaderRoute: typeof TreinarTurmaStudioTopFitnessRouteImport
      parentRoute: typeof TreinarTurmaRoute
    }
    '/treinar/turma/ct-ishigeki/': {
      id: '/treinar/turma/ct-ishigeki/'
      path: '/'
      fullPath: '/treinar/turma/ct-ishigeki/'
      preLoaderRoute: typeof TreinarTurmaCtIshigekiIndexRouteImport
      parentRoute: typeof TreinarTurmaCtIshigekiRoute
    }
    '/treinar/turma/ct-ishigeki/interesse': {
      id: '/treinar/turma/ct-ishigeki/interesse'
      path: '/interesse'
      fullPath: '/treinar/turma/ct-ishigeki/interesse'
      preLoaderRoute: typeof TreinarTurmaCtIshigekiInteresseRouteImport
      parentRoute: typeof TreinarTurmaCtIshigekiRoute
    }
    '/treinar/turma/studio-top-fitness/': {
      id: '/treinar/turma/studio-top-fitness/'
      path: '/'
      fullPath: '/treinar/turma/studio-top-fitness/'
      preLoaderRoute: typeof TreinarTurmaStudioTopFitnessIndexRouteImport
      parentRoute: typeof TreinarTurmaStudioTopFitnessRoute
    }
    '/treinar/turma/studio-top-fitness/interesse': {
      id: '/treinar/turma/studio-top-fitness/interesse'
      path: '/interesse'
      fullPath: '/treinar/turma/studio-top-fitness/interesse'
      preLoaderRoute: typeof TreinarTurmaStudioTopFitnessInteresseRouteImport
      parentRoute: typeof TreinarTurmaStudioTopFitnessRoute
    }
  }
}

interface TreinarMuaythaiRouteChildren {
  TreinarMuaythaiAgendarRoute: typeof TreinarMuaythaiAgendarRoute
  TreinarMuaythaiIndexRoute: typeof TreinarMuaythaiIndexRoute
}

const TreinarMuaythaiRouteChildren: TreinarMuaythaiRouteChildren = {
  TreinarMuaythaiAgendarRoute: TreinarMuaythaiAgendarRoute,
  TreinarMuaythaiIndexRoute: TreinarMuaythaiIndexRoute,
}

const TreinarMuaythaiRouteWithChildren = TreinarMuaythaiRoute._addFileChildren(
  TreinarMuaythaiRouteChildren,
)

interface TreinarPersonalRouteChildren {
  TreinarPersonalAgendarRoute: typeof TreinarPersonalAgendarRoute
  TreinarPersonalIndexRoute: typeof TreinarPersonalIndexRoute
}

const TreinarPersonalRouteChildren: TreinarPersonalRouteChildren = {
  TreinarPersonalAgendarRoute: TreinarPersonalAgendarRoute,
  TreinarPersonalIndexRoute: TreinarPersonalIndexRoute,
}

const TreinarPersonalRouteWithChildren = TreinarPersonalRoute._addFileChildren(
  TreinarPersonalRouteChildren,
)

interface TreinarTurmaCtIshigekiRouteChildren {
  TreinarTurmaCtIshigekiInteresseRoute: typeof TreinarTurmaCtIshigekiInteresseRoute
  TreinarTurmaCtIshigekiIndexRoute: typeof TreinarTurmaCtIshigekiIndexRoute
}

const TreinarTurmaCtIshigekiRouteChildren: TreinarTurmaCtIshigekiRouteChildren =
  {
    TreinarTurmaCtIshigekiInteresseRoute: TreinarTurmaCtIshigekiInteresseRoute,
    TreinarTurmaCtIshigekiIndexRoute: TreinarTurmaCtIshigekiIndexRoute,
  }

const TreinarTurmaCtIshigekiRouteWithChildren =
  TreinarTurmaCtIshigekiRoute._addFileChildren(
    TreinarTurmaCtIshigekiRouteChildren,
  )

interface TreinarTurmaStudioTopFitnessRouteChildren {
  TreinarTurmaStudioTopFitnessInteresseRoute: typeof TreinarTurmaStudioTopFitnessInteresseRoute
  TreinarTurmaStudioTopFitnessIndexRoute: typeof TreinarTurmaStudioTopFitnessIndexRoute
}

const TreinarTurmaStudioTopFitnessRouteChildren: TreinarTurmaStudioTopFitnessRouteChildren =
  {
    TreinarTurmaStudioTopFitnessInteresseRoute:
      TreinarTurmaStudioTopFitnessInteresseRoute,
    TreinarTurmaStudioTopFitnessIndexRoute:
      TreinarTurmaStudioTopFitnessIndexRoute,
  }

const TreinarTurmaStudioTopFitnessRouteWithChildren =
  TreinarTurmaStudioTopFitnessRoute._addFileChildren(
    TreinarTurmaStudioTopFitnessRouteChildren,
  )

interface TreinarTurmaRouteChildren {
  TreinarTurmaCtIshigekiRoute: typeof TreinarTurmaCtIshigekiRouteWithChildren
  TreinarTurmaStudioTopFitnessRoute: typeof TreinarTurmaStudioTopFitnessRouteWithChildren
  TreinarTurmaIndexRoute: typeof TreinarTurmaIndexRoute
}

const TreinarTurmaRouteChildren: TreinarTurmaRouteChildren = {
  TreinarTurmaCtIshigekiRoute: TreinarTurmaCtIshigekiRouteWithChildren,
  TreinarTurmaStudioTopFitnessRoute:
    TreinarTurmaStudioTopFitnessRouteWithChildren,
  TreinarTurmaIndexRoute: TreinarTurmaIndexRoute,
}

const TreinarTurmaRouteWithChildren = TreinarTurmaRoute._addFileChildren(
  TreinarTurmaRouteChildren,
)

interface TreinarRouteChildren {
  TreinarMuaythaiRoute: typeof TreinarMuaythaiRouteWithChildren
  TreinarPersonalRoute: typeof TreinarPersonalRouteWithChildren
  TreinarTurmaRoute: typeof TreinarTurmaRouteWithChildren
  TreinarIndexRoute: typeof TreinarIndexRoute
}

const TreinarRouteChildren: TreinarRouteChildren = {
  TreinarMuaythaiRoute: TreinarMuaythaiRouteWithChildren,
  TreinarPersonalRoute: TreinarPersonalRouteWithChildren,
  TreinarTurmaRoute: TreinarTurmaRouteWithChildren,
  TreinarIndexRoute: TreinarIndexRoute,
}

const TreinarRouteWithChildren =
  TreinarRoute._addFileChildren(TreinarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreinarRoute: TreinarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
